{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: microdrop.droplet-planning-plugin
  version: {{ GIT_VERSION }}

build:
  number: 0
  script: python -m mpm.bin.build

requirements:
  build:
    #: .. versionadded:: 2.4
    - logging-helpers >=0.4
    #: .. versionchanged:: 2.4
    - microdrop >=2.25
    - microdrop-plugin-manager >=0.14
    - pandas
    - path_helpers >=0.2.post4
    - pyyaml
    - si-prefix
    - wheeler.pygtkhelpers
    - zmq-plugin >=0.2.post2

  run:
    #: .. versionadded:: 2.4
    - logging-helpers >=0.4
    #: .. versionchanged:: 2.4
    - microdrop >=2.25
    - microdrop-plugin-manager >=0.14
    - pandas
    - path_helpers >=0.2.post4
    - pyyaml
    - si-prefix
    - wheeler.pygtkhelpers
    - zmq-plugin >=0.2.post2

test:
  commands:
    - python -m mpm.bin.import_test -a {{ PKG_NAME }}

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: BSD
